<?php if ($wo['loggedin'] == true && Wo_IsMobile() == false) { ?>
<div class="left-sidebar">
	<ul>
		<!--<li>
			<a href="<?php echo $wo['user']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username'];?>">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#047cac" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z" /></svg> <?php echo $wo['lang']['my_profile'];?>
			</a>
		</li>-->
		<li class="wow_side_post_fltr">
			<a href="<?php echo $wo['config']['site_url']; ?>" data-ajax="?index.php?link1=home">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#047cac" d="M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z"/></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/home.svg"> <?php echo $wo['lang']['news_feed'];?>
			</a>
			<?php if ($wo['page'] == 'home') { ?>
			<?php if ($wo['config']['order_posts_by'] == 0) { ?>
				<div class="dropdown order_by">
					<svg class="dropdown-toggle" data-toggle="dropdown" role="button" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="currentColor" d="M7,10L12,15L17,10H7Z" opacity="0.7"/></svg>
					<ul class="dropdown-menu dropdown-menu-right" role="button">
						<li class="order_all <?php echo ($wo['user']['order_posts_by'] == 0) ? 'active' : ''; ?>"><a href="javascript:void(0);" onclick="Wo_StorePosts(0);"><?php echo $wo['lang']['all'] ?></a></li>
						<li class="order_people <?php echo ($wo['user']['order_posts_by'] == 1) ? 'active' : ''; ?>"><a href="javascript:void(0);" onclick="Wo_StorePosts(1);"><?php echo $wo['lang']['people_i_follow'] ?></a></li>
					</ul>
				</div>
			<?php } ?>
			<?php } ?>
		</li>
		<?php if ($wo['config']['website_mode'] != 'askfm' && $wo['config']['website_mode'] != 'instagram') { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=albums'); ?>" data-ajax="?link1=albums">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#8bc34a" d="M22,16V4A2,2 0 0,0 20,2H8A2,2 0 0,0 6,4V16A2,2 0 0,0 8,18H20A2,2 0 0,0 22,16M11,12L13.03,14.71L16,11L20,16H8M2,6V20A2,2 0 0,0 4,22H18V20H4V6" /></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/album.svg"> <?php echo $wo['lang']['albums'];?>
			</a>
		</li>
		<?php } ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=saved-posts');?>" data-ajax="?link1=saved-posts">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#673ab7" d="M17,3H7A2,2 0 0,0 5,5V21L12,18L19,21V5C19,3.89 18.1,3 17,3Z"></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/save.svg"> <?php echo $wo['lang']['saved_posts'];?>
			</a>
		</li>
		<?php if ($wo['config']['popular_posts'] == 1) { ?>
		<li>
			<a href="<?php echo $wo['config']['site_url']; ?>/most_liked" data-ajax="?link1=most_liked">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#8d73cc" d="M20 22H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1zm-1-2V4H5v16h14zM7 6h4v4H7V6zm0 6h10v2H7v-2zm0 4h10v2H7v-2zm6-9h4v2h-4V7z"></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/popular.svg"> <?php echo TextForMode('popular_posts');?>
			</a>
		</li>
		<?php } ?>
		<?php if ($wo['config']['memories_system'] == 1) { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=memories'); ?>" data-ajax="?link1=memories">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#009da0" d="M13.5,8H12V13L16.28,15.54L17,14.33L13.5,12.25V8M13,3A9,9 0 0,0 4,12H1L4.96,16.03L9,12H6A7,7 0 0,1 13,5A7,7 0 0,1 20,12A7,7 0 0,1 13,19C11.07,19 9.32,18.21 8.06,16.94L6.64,18.36C8.27,20 10.5,21 13,21A9,9 0 0,0 22,12A9,9 0 0,0 13,3"></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/memories.svg"> <?php echo $wo['lang']['memories'];?>
			</a>
		</li>
		<?php } ?>
		<?php if ($wo['config']['poke_system'] == 1) { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=poke');?>"  data-ajax="?link1=poke">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#009688" d="M21,9A1,1 0 0,1 22,10A1,1 0 0,1 21,11H16.53L16.4,12.21L14.2,17.15C14,17.65 13.47,18 12.86,18H8.5C7.7,18 7,17.27 7,16.5V10C7,9.61 7.16,9.26 7.43,9L11.63,4.1L12.4,4.84C12.6,5.03 12.72,5.29 12.72,5.58L12.69,5.8L11,9H21M2,18V10H5V18H2Z"></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/poke.svg"> <?php echo $wo['lang']['pokes'];?>
			</a>
		</li>
		<?php } ?>
		<?php if ($wo['config']['groups'] == 1) { 
			$my_groups_text = $wo['lang']['my_groups'];
			$my_groups_page = 'groups';
			if (!$wo['config']['can_use_groups']) {
				$my_groups_text = $wo['lang']['joined_groups'];
			  $my_groups_page = 'joined_groups';
			}
			?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1='.$my_groups_page); ?>" data-ajax="?link1=<?php echo $my_groups_page; ?>">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#03A9F4" d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z"></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/group.svg"> <?php echo $my_groups_text;?>
			</a>
		</li>
		<?php } ?>
		<?php if ($wo['config']['pages'] == 1) { 
			$my_pages_text = $wo['lang']['my_pages'];
			$my_pages_page = 'pages';
			if (!$wo['config']['can_use_pages']) {
				$my_pages_text = $wo['lang']['liked_pages'];
			  $my_pages_page = 'liked-pages';
			}
		?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1='.$my_pages_page); ?>" data-ajax="?link1=<?php echo $my_pages_page; ?>">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#f79f58" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z"></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/page.svg"> <?php echo $my_pages_text;?>
			</a>
		</li>
		<?php } ?>




        <li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=search?query=');?>" data-ajax="?link1=search">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#8BC34A" d="M14.19,14.19L6,18L9.81,9.81L18,6M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,10.9A1.1,1.1 0 0,0 10.9,12A1.1,1.1 0 0,0 12,13.1A1.1,1.1 0 0,0 13.1,12A1.1,1.1 0 0,0 12,10.9Z"></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/explore.svg"> <?php echo ($wo['config']['website_mode'] == 'instagram') ? $wo['lang']['search'] : $wo['lang']['explore'];?>
			</a>
		</li>
		<?php if ($wo['config']['website_mode'] == 'instagram') { ?>
			<li>
				<a href="<?php echo Wo_SeoLink('index.php?link1=explore');?>" data-ajax="?link1=explore">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#8BC34A" d="M14.19,14.19L6,18L9.81,9.81L18,6M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,10.9A1.1,1.1 0 0,0 10.9,12A1.1,1.1 0 0,0 12,13.1A1.1,1.1 0 0,0 13.1,12A1.1,1.1 0 0,0 12,10.9Z"></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/explorein.svg"> <?php echo $wo['lang']['explore'];?>
				</a>
			</li>
		<?php } ?>
		






		
		<?php if ($wo['config']['find_friends'] == 1) { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=friends-nearby'); ?>" data-ajax="?link1=friends-nearby">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#b2c17c" d="M15.5,12C18,12 20,14 20,16.5C20,17.38 19.75,18.21 19.31,18.9L22.39,22L21,23.39L17.88,20.32C17.19,20.75 16.37,21 15.5,21C13,21 11,19 11,16.5C11,14 13,12 15.5,12M15.5,14A2.5,2.5 0 0,0 13,16.5A2.5,2.5 0 0,0 15.5,19A2.5,2.5 0 0,0 18,16.5A2.5,2.5 0 0,0 15.5,14M10,4A4,4 0 0,1 14,8C14,8.91 13.69,9.75 13.18,10.43C12.32,10.75 11.55,11.26 10.91,11.9L10,12A4,4 0 0,1 6,8A4,4 0 0,1 10,4M2,20V18C2,15.88 5.31,14.14 9.5,14C9.18,14.78 9,15.62 9,16.5C9,17.79 9.38,19 10,20H2Z"></svg><img src="<?php echo $wo['config']['theme_url'];?>/img/sidebar/find.svg"> <?php echo $wo['lang']['find_friends'];?>
			</a>
		</li>
		<?php } ?>



	</ul>
</div>
<?php } ?>


<?php if ($wo['config']['order_posts_by'] == 0) { ?>
<script>
function Wo_StorePosts(type) {
  if (type > 1) {
     return false;
  }
  if (type == 0) {
	$('.order_all').addClass('active');
	$('.order_people').removeClass('active');
  } else {
	$('.order_all').removeClass('active');
	$('.order_people').addClass('active');
  }
  $('#posts-laoded').html('<div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div><div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div>');
  $.get(Wo_Ajax_Requests_File() + '?f=update_order_by', {type:type}, function (data) {
    if (data.status == 200) {
      loadposts();
    }
  });
}
</script>
<?php } ?>